### ISSUE TITLE
question about UI

### ISSUE THREAD

**Issue by chively** [sangjw2/tetris_plus#5]
이번주는 UI 형식만 생각하면 되는건가요?

**Comment by sangjw2** [comment]
아마도 피그마를 활용해서 UI  메인메뉴, 게임화면 디자인 하는 것하고 아이템 구현할 것들 3가지 정도로 추리는 것 하면 될 것 같아요

**Comment by chively** [comment]
https://www.figma.com/file/jpeb275qV681wC4VkmxREr/Untitled?type=design&node-id=0-1&mode=design&t=bagAX65at9VoAbzZ-0
